reown-com/appkit-react-native

package.json
src/components/WalletItem.tsx
yarn.lock

Updated version of universal provider to solve issues with localStorage and document objects

fix: updated universal provider version to fix issue in RN

---

example/package.json
example/src/screens/App.tsx
example/yarn.lock
src/components/WalletItem.tsx
src/components/Web3Modal.tsx
src/controllers/ConfigCtrl.ts
src/hooks/useConfigure.ts
src/index.tsx
src/types/controllerTypes.ts
src/utils/StorageUtil.ts
src/views/Account.tsx

* Applying polyfills in the main file of the SDK to simplify installation process for devs
* Setting localstorage key with wallet data after the session is created
* Added a config value to save the data temporarily
* Added ethers as a dependency of the example app

Moved polyfills & improved deep link handling

---

src/components/WalletItem.tsx
src/utils/StorageUtil.ts

*  Saving deeplink of selected wallet for redirections (previously saving universal link)

fix: saving deeplink

---

example/App.js
example/eas-update-config.ts
package.json
yarn.lock

Updated `@walletconnect/react-native-compat` & `@walletconnect/universal-provider` to 2.7.6

chore: updated walletconnect deps

---

example/app.config.js
example/src/constants/Config.ts
package.json
src/types/coreTypes.ts
yarn.lock

* Updated deps
* Added `redirect` param as mandatory to provider's metadata

update deps + redirect param

---

src/components/NavHeader.tsx
src/constants/Routes.ts
src/controllers/ModalCtrl.ts

* checking route stack to add back button
* added account as an `open()` valid route

fix: navigation options

---

src/hooks/useConfigure.ts

* Fixed theme change flickering when using listeners. [Issue with listeners](https://github.com/expo/expo/issues/10815#issuecomment-719113200)

fix: theme change 

---

example/src/screens/App.tsx
src/assets/Checkmark.tsx
src/components/ModalToast.tsx
src/components/Web3Modal.tsx
src/components/Web3Text.tsx
src/controllers/ToastCtrl.ts
src/hooks/useConfigure.ts
src/types/controllerTypes.ts
src/utils/ExplorerUtil.ts
src/views/Account.tsx
src/views/QRCodeView.tsx

Added toast messages to replace native alerts
https://github.com/WalletConnect/web3modal-react-native/assets/25931366/7336988f-3e56-440f-baf9-3d243f048779

feat: added toast messages

---

example/src/utils/MethodUtil.ts

- Added `data` to sendTransaction code
- using ethers `_legacySignMessage`

fix: changed sign and sendTransaction examples

---

packages/core/src/controllers/OptionsController.ts
packages/scaffold/src/partials/w3m-connecting-header/index.tsx
packages/scaffold/src/partials/w3m-connecting-mobile/index.tsx
packages/scaffold/src/partials/w3m-connecting-qrcode/index.tsx
packages/scaffold/src/partials/w3m-connecting-web/index.tsx
packages/scaffold/src/partials/w3m-connecting-web/styles.ts
packages/scaffold/src/views/w3m-account-view/index.tsx
packages/scaffold/src/views/w3m-connecting-view/index.tsx

* Added web wallet support
* Added platform tab in connecting view
* Code improvements
https://github.com/WalletConnect/web3modal-react-native/assets/25931366/095977bf-8fe1-498d-8412-633e36f1dac4
https://github.com/WalletConnect/web3modal-react-native/assets/25931366/79879e3e-9fc1-4bdd-8d0e-3e0c33655fad

feat: Web wallets + Platform tab

---

apps/gallery/stories/components/LoadingThumbnail.stories.tsx
packages/scaffold/src/modal/w3m-router/index.tsx
packages/scaffold/src/partials/w3m-connecting-mobile/index.tsx
packages/scaffold/src/partials/w3m-connecting-mobile/styles.ts
packages/scaffold/src/partials/w3m-connecting-web/index.tsx
packages/scaffold/src/views/w3m-network-switch-view/index.tsx
packages/scaffold/src/views/w3m-network-switch-view/styles.ts
packages/scaffold/src/views/w3m-networks-view/index.tsx
packages/ui/src/components/wui-loading-hexagon/index.tsx
packages/ui/src/components/wui-loading-thumbnail/index.tsx

* Added network switching view
* Small UI fix in networks view
https://github.com/WalletConnect/web3modal-react-native/assets/25931366/de051c51-5981-432b-a324-0583119bc34f

feat: Switch network

---

apps/native/package.json
package.json
packages/core/package.json
packages/scaffold/package.json
packages/ui/package.json
packages/wagmi/package.json
yarn.lock

* Moved all devDependencies to root package.json
* Fixed devDependencies package versions

chore: moved devDependencies to root file

---

packages/core/package.json
yarn.lock

* Downgraded valtio to 1.10.5 until they solve issues with hermes

fix: downgraded valtio to 1.10.5

---

.changeset/eighty-dancers-roll.md
.changeset/pre.json
apps/gallery/CHANGELOG.md
apps/gallery/package.json
apps/native/CHANGELOG.md
apps/native/package.json
package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/scaffold/CHANGELOG.md
packages/scaffold/package.json
packages/ui/CHANGELOG.md
packages/ui/package.json
packages/wagmi/CHANGELOG.md
packages/wagmi/package.json
packages/wagmi/src/utils/constants.ts
yarn.lock

* fix: improved page loading shimmer items by @ignaciosantise in https://github.com/WalletConnect/web3modal-react-native/pull/77
* UI improvements by @ignaciosantise in https://github.com/WalletConnect/web3modal-react-native/pull/81
* fix: clear linking if qr is pressed by @ignaciosantise in https://github.com/WalletConnect/web3modal-react-native/pull/82
* fix: using asyncstorage in connector by @ignaciosantise in https://github.com/WalletConnect/web3modal-react-native/pull/84
* fix: changed zIndex of close button to make it pressable by @ignaciosantise in https://github.com/WalletConnect/web3modal-react-native/pull/88
* fix: disabled nativeDriver in button animations by @ignaciosantise in https://github.com/WalletConnect/web3modal-react-native/pull/89
* fix: downgraded valtio to 1.10.5 …

chore: bumped version to alpha.14

---

packages/scaffold/src/partials/w3m-connecting-mobile/index.tsx
packages/scaffold/src/partials/w3m-connecting-mobile/styles.ts
packages/scaffold/src/partials/w3m-connecting-web/index.tsx
packages/scaffold/src/partials/w3m-connecting-web/styles.ts
packages/scaffold/src/views/w3m-account-view/index.tsx
packages/scaffold/src/views/w3m-connect-view/index.tsx
packages/scaffold/src/views/w3m-get-wallet-view/index.tsx
packages/scaffold/src/views/w3m-networks-view/index.tsx
packages/scaffold/src/views/w3m-what-is-a-network-view/index.tsx
packages/scaffold/src/views/w3m-what-is-a-wallet-view/index.tsx
packages/ui/src/composites/wui-button/styles.ts
packages/ui/src/composites/wui-input-text/styles.ts
packages/ui/src/composites/wui-list-item/index.tsx
packages/ui/src/composites/wui-list-item/styles.ts
packages/ui/src/composites/wui-search-bar/index.tsx

* UI improvements based on design team feedback
* Added condition in copy buttons

UI improvements

---

.changeset/dull-suns-swim.md
.changeset/early-toes-film.md
.changeset/eighty-dancers-roll.md
.changeset/eighty-planes-double.md
.changeset/four-suns-draw.md
.changeset/gentle-chairs-retire.md
.changeset/nasty-ears-smash.md
.changeset/pre.json
.changeset/sharp-apples-boil.md
.changeset/sharp-socks-repair.md
.changeset/shy-readers-itch.md
.changeset/slimy-moons-buy.md
.changeset/wicked-phones-mix.md
apps/gallery/CHANGELOG.md
apps/gallery/package.json
apps/native/CHANGELOG.md
apps/native/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/scaffold/CHANGELOG.md
packages/scaffold/package.json
packages/ui/CHANGELOG.md
packages/ui/package.json
packages/wagmi/CHANGELOG.md
packages/wagmi/package.json
packages/wagmi/src/utils/constants.ts

* Fix/remove gap by @ignaciosantise in https://github.com/WalletConnect/web3modal-react-native/pull/93
* UI improvements by @ignaciosantise in https://github.com/WalletConnect/web3modal-react-native/pull/94
**Full Changelog**: https://github.com/WalletConnect/web3modal-react-native/compare/v1.0.0-alpha.14...v1.0.0-beta.1

chore: prep for v1.0.0-beta.1

---

.changeset/pre.json
.changeset/slimy-dancers-compete.md
apps/gallery/CHANGELOG.md
apps/gallery/package.json
apps/native/CHANGELOG.md
apps/native/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/scaffold/CHANGELOG.md
packages/scaffold/package.json
packages/ui/CHANGELOG.md
packages/ui/package.json
packages/wagmi/CHANGELOG.md
packages/wagmi/package.json
packages/wagmi/src/utils/constants.ts

* chore: ui fixes by @ignaciosantise in https://github.com/WalletConnect/web3modal-react-native/pull/96
**Full Changelog**: https://github.com/WalletConnect/web3modal-react-native/compare/v1.0.0-beta.1...v1.0.0-beta.2

chore: prep for v1.0.0-beta.2

---

packages/scaffold/src/partials/w3m-connecting-mobile/index.tsx
packages/scaffold/src/partials/w3m-connecting-web/styles.ts
packages/scaffold/src/views/w3m-network-switch-view/index.tsx
packages/scaffold/src/views/w3m-networks-view/index.tsx
packages/ui/src/composites/wui-account-button/index.tsx
packages/ui/src/composites/wui-list-item/index.tsx
packages/ui/src/utils/ThemeUtil.ts

chore: ui improvements

---

packages/core/src/controllers/ApiController.ts

* Send OS and version in api calls

fix: sending os and version in api call

---

.changeset/pre.json
.changeset/rare-goats-accept.md
apps/gallery/CHANGELOG.md
apps/gallery/package.json
apps/native/CHANGELOG.md
apps/native/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/scaffold/CHANGELOG.md
packages/scaffold/package.json
packages/ui/CHANGELOG.md
packages/ui/package.json
packages/wagmi/CHANGELOG.md
packages/wagmi/package.json
packages/wagmi/src/utils/constants.ts

* chore: ui improvements by @ignaciosantise in https://github.com/WalletConnect/web3modal-react-native/pull/99
* refactor: updated deps by @ignaciosantise in https://github.com/WalletConnect/web3modal-react-native/pull/100
* fix: sending os and version in api call by @ignaciosantise in https://github.com/WalletConnect/web3modal-react-native/pull/101
**If you are updating from an older version you need to add some changes to your code:**
1. Install `@walletconnect/react-native-compat` v2.10.5
2. Run `pod install` from your ios folder
3. Add `import from "@walletconnect/react-native-compat" in your app's root file (before importing wagmi or web3modal)
**Full Changelog**: https://github.com/WalletConnect/web3modal-react-native/compare/v1.0.0-beta.2...v1.0.0-beta.3

chore: prep for v1.0.0-beta.3

---

packages/scaffold/src/client.ts
packages/scaffold/src/modal/w3m-account-button/index.tsx
packages/scaffold/src/partials/w3m-all-wallets-list/index.tsx
packages/scaffold/src/views/w3m-account-view/index.tsx
packages/scaffold/src/views/w3m-connect-view/index.tsx
packages/ui/src/composites/wui-icon-box/index.tsx
packages/wagmi/src/client.ts

* Solved edge case with `includeWalletIds` prop
* Filter recent wallets with `includeWalletIds` and `excludeWalletIds`
* Use network image if its provided in `chainImages` prop
* UI: resized disconnect icon

Small fixes

---

apps/gallery/CHANGELOG.md
apps/gallery/package.json
apps/native/CHANGELOG.md
apps/native/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/scaffold/CHANGELOG.md
packages/scaffold/package.json
packages/ui/CHANGELOG.md
packages/ui/package.json
packages/wagmi/CHANGELOG.md
packages/wagmi/package.json
packages/wagmi/src/utils/constants.ts

* fix: change account UI margin left by @crypblizz8 in https://github.com/WalletConnect/web3modal-react-native/pull/105
* fix: version constant by @ignaciosantise in https://github.com/WalletConnect/web3modal-react-native/pull/106
**Full Changelog**: https://github.com/WalletConnect/web3modal-react-native/compare/v1.0.0...v1.0.1

chore: prep for v1.0.1

---

.github/workflows/ci.yml
.github/workflows/code_quality.yml
jest.config.ts
packages/core/package.json
packages/ui/package.json
qodana.yaml

* Added qodana config to scan code and upload code coverage report

chore: added qodana config

---

packages/scaffold/src/views/w3m-connect-view/index.tsx

* Added installed check in recent wallets

fix: added installed prop in recent wallets

---

apps/native/App.tsx
packages/scaffold/src/modal/w3m-network-button/index.tsx
packages/scaffold/src/views/w3m-networks-view/index.tsx
packages/ui/src/composites/wui-network-button/index.tsx
packages/ui/src/composites/wui-network-button/styles.ts
packages/wagmi/src/index.tsx

* Export network button in wagmi package
* UI improvements in network button
https://github.com/WalletConnect/web3modal-react-native/assets/25931366/7266f1b6-c0d2-4803-a11b-dd4016218d36
https://github.com/WalletConnect/web3modal-react-native/assets/25931366/c78e0629-8784-4864-81e8-3ecbe12dd5bd

feat: exporting network button + ui improvements

---

apps/gallery/CHANGELOG.md
apps/gallery/package.json
apps/native-cli/CHANGELOG.md
apps/native-cli/package.json
apps/native/CHANGELOG.md
apps/native/package.json
packages/coinbase/CHANGELOG.md
packages/coinbase/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/scaffold-utils/CHANGELOG.md
packages/scaffold-utils/package.json
packages/scaffold-utils/src/utils/ConstantsUtil.ts
packages/scaffold/CHANGELOG.md
packages/scaffold/package.json
packages/ui/CHANGELOG.md
packages/ui/package.json
packages/wagmi/CHANGELOG.md
packages/wagmi/package.json
yarn.lock

* fix: solve issue in chain switching @ignaciosantise in https://github.com/WalletConnect/web3modal-react-native/pull/122
* feat: export network button by @ignaciosantise in https://github.com/WalletConnect/web3modal-react-native/pull/123
**Full Changelog**: https://github.com/WalletConnect/web3modal-react-native/compare/v1.1.0...v1.1.1

chore: bump to 1.1.1

---

apps/gallery/package.json
apps/native-cli/package.json
apps/native/package.json
packages/coinbase-ethers/CHANGELOG.md
packages/coinbase-ethers/package.json
packages/coinbase-wagmi/CHANGELOG.md
packages/coinbase-wagmi/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/ethers5/CHANGELOG.md
packages/ethers5/package.json
packages/scaffold-utils/CHANGELOG.md
packages/scaffold-utils/package.json
packages/scaffold-utils/src/utils/ConstantsUtil.ts
packages/scaffold/CHANGELOG.md
packages/scaffold/package.json
packages/ui/CHANGELOG.md
packages/ui/package.json
packages/wagmi/CHANGELOG.md
packages/wagmi/package.json
yarn.lock

* feat: add custom wallets prop by @ignaciosantise in https://github.com/WalletConnect/web3modal-react-native/pull/128
* feat: add modal package compatible with ethers5 by @ignaciosantise in https://github.com/WalletConnect/web3modal-react-native/pull/129
**Full Changelog**: https://github.com/WalletConnect/web3modal-react-native/compare/v1.1.1...v1.2.0

chore: prep for v1.2.0

---

.changeset/orange-chefs-juggle.md
.changeset/pre.json
apps/native-cli/CHANGELOG.md
apps/native-cli/package.json
apps/native/CHANGELOG.md
apps/native/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/ethers/CHANGELOG.md
packages/ethers/package.json
packages/ethers5/CHANGELOG.md
packages/ethers5/package.json
packages/scaffold-utils/CHANGELOG.md
packages/scaffold-utils/package.json
packages/scaffold-utils/src/utils/ConstantsUtil.ts
packages/scaffold/CHANGELOG.md
packages/scaffold/package.json
packages/wagmi/CHANGELOG.md
packages/wagmi/package.json
yarn.lock

* Fix/analytics by @ignaciosantise in https://github.com/WalletConnect/web3modal-react-native/pull/143
**Full Changelog**: https://github.com/WalletConnect/web3modal-react-native/compare/v1.3.0-alpha.0...v1.3.0-alpha.1

chore/prep 1.3.0-alpha.1

---

packages/core/src/controllers/ApiController.ts
packages/core/src/controllers/ConnectionController.ts
packages/core/src/utils/FetchUtil.ts

* fix: Load image with custom headers using fetch
* fix: Solved Expo error "Failed to get size for image"

fix: load image with headers

---

packages/email-wagmi/src/index.ts
packages/email/src/W3mEmailWebview.tsx

* fix: wait for email provider to init before using it
* fix: show email request popup only for unsafe methods

fix: use email provider after init

---

packages/ethers/src/client.ts
packages/ethers5/src/client.ts

* Get identity from blockchain api before using ethers providers

fix: ethers lookup

---

packages/ethers/src/index.tsx
packages/ethers5/src/index.tsx

* Export useWalletInfo hook in ethers packages
docs: https://docs.walletconnect.com/appkit/react-native/core/hooks?platform=ethers#usewalletinfo

feat: wallet info hook

---

packages/ethers/src/client.ts
packages/ethers5/src/client.ts

Updated the condition to send add chain request to only check for user rejection in ethers clients

fix: wallet_addEthereumChain condition in ethers

---

packages/core/src/utils/ConstantsUtil.ts
packages/core/src/utils/CoreHelperUtil.ts
packages/email/src/W3mFrameHelpers.ts

chore: removed fallback org logic

---

packages/core/src/__tests__/controllers/AssetController.test.ts
packages/core/src/controllers/BlockchainApiController.ts

chore: missing org fallback

---

package.json
packages/common/src/index.ts
packages/common/src/utils/ConstantsUtil.ts
packages/core/package.json
packages/core/src/__tests__/controllers/AssetController.test.ts
packages/core/src/controllers/BlockchainApiController.ts
packages/core/src/utils/ConstantsUtil.ts
packages/core/src/utils/CoreHelperUtil.ts
packages/core/src/utils/FetchUtil.ts
packages/email/src/W3mFrameHelpers.ts
packages/ethers/src/client.ts
packages/ethers5/src/client.ts
packages/scaffold/src/client.ts
packages/wagmi/src/client.ts

* Ethers switchChain improvements
* Send clientId in blockchain api requests
* removed .org fallback
* moved some constants to common package
https://linear.app/walletconnect/issue/APKTN-184/[rn]-add-clientid-params-to-blockchain-api-endpoints

chore: improvements

---

.changeset/soft-grapes-behave.md
packages/core/src/utils/ConstantsUtil.ts
packages/core/src/utils/CoreHelperUtil.ts
packages/scaffold/src/partials/w3m-connecting-mobile/components/Body.tsx
packages/scaffold/src/partials/w3m-connecting-mobile/components/StoreLink.tsx
packages/scaffold/src/partials/w3m-connecting-mobile/index.tsx
packages/scaffold/src/partials/w3m-connecting-mobile/styles.ts
packages/scaffold/src/partials/w3m-connecting-web/components/Body.tsx
packages/scaffold/src/partials/w3m-connecting-web/index.tsx
packages/scaffold/src/partials/w3m-connecting-web/styles.ts

* Showing a default error in case there's an exception not related to linking
* Small refactor of components

fix: added a default error in connecting view

---

.github/workflows/changesets.yml

fix: removed extra env in GH action

---

.changeset/empty-apes-taste.md
packages/siwe/src/scaffold/partials/w3m-connecting-siwe/index.tsx
packages/siwe/src/scaffold/partials/w3m-connecting-siwe/styles.ts
yarn.lock

Show user avatar when there's no wallet icon available

fix: show user  avatar in Sign In screen as fallback

---

.changeset/bright-ligers-help.md
packages/ethers/src/utils/defaultConfig.ts
packages/ethers5/src/utils/defaultConfig.ts

Marked `extraConnectors` prop as optional in ethers default config

fix: optional extraConnectors prop

---

.changeset/curly-squids-complain.md
packages/core/src/utils/TypeUtil.ts
packages/scaffold/src/partials/w3m-connecting-mobile/index.tsx
packages/scaffold/src/partials/w3m-connecting-web/index.tsx
packages/scaffold/src/views/w3m-all-wallets-view/index.tsx
packages/scaffold/src/views/w3m-connect-view/index.tsx
packages/scaffold/src/views/w3m-connecting-external-view/index.tsx

* Send wallet id in SELECT_WALLET and CONNECT_SUCCESS events
https://linear.app/walletconnect/issue/APKTN-228/%5Breact-native%5D-update-connect-success-and-select-wallet-events

chore: event updates

---

.changeset/angry-tips-tan.md
apps/native/src/utils/SiweUtils.ts
packages/ethers/src/client.ts
packages/ethers5/src/client.ts
packages/scaffold/src/modal/w3m-modal/index.tsx
packages/siwe/src/controller/SIWEController.ts
packages/wagmi/src/client.ts

* onNewAddress improvements
* Fixes session checks as the session can be an empty object resulting in always being truthy.
* Checks against the address in the current session, which is more reliable than previousAddress state variable.
* Fixes a bug where closing the modal would call disconnect even if the user wasn't connected
Based on: https://github.com/WalletConnect/web3modal/pull/2507

fix: siwe - session checks & improvements

---

.changeset/breezy-dogs-flow.md
packages/scaffold/src/modal/w3m-modal/index.tsx

fix: solved overlap of modal & sign screen in email siwe on some Android devices
https://github.com/user-attachments/assets/fe87d0dc-a667-42c6-bd42-eb3b48521dd0
https://github.com/user-attachments/assets/ba80c91b-b8da-499f-a6dd-b97cfa9f6d82

fix: solved overlap of modal & sign screen in email siwe

---

.changeset/calm-brooms-join.md
packages/core/src/controllers/ApiController.ts

chore: add origin header to w3m api

---

.changeset/funny-items-pay.md
packages/core/src/controllers/ApiController.ts

added react-native version to api header

chore: added rn version to api header

---

packages/scaffold/src/partials/w3m-account-tokens/index.tsx
packages/scaffold/src/partials/w3m-account-wallet-features/index.tsx
packages/scaffold/src/partials/w3m-account-wallet-features/styles.ts
packages/scaffold/src/views/w3m-wallet-compatible-networks-view/index.tsx
packages/ui/src/composites/wui-list-token/index.tsx
packages/ui/src/composites/wui-list-token/styles.ts
packages/ui/src/index.ts
packages/ui/src/utils/UiUtil.ts

Show token list if available
https://github.com/user-attachments/assets/cb41351c-f570-4b45-8a64-f58b62eb4aa1
https://github.com/user-attachments/assets/c741b75e-4bca-4447-894a-4fbfae12f756
https://linear.app/walletconnect/issue/APKTN-209/view-asset-balances

feat: wallet token list

---

packages/common/package.json
packages/common/src/index.ts
packages/common/src/utils/DateUtil.ts
packages/common/src/utils/TypeUtil.ts
packages/core/src/controllers/BlockchainApiController.ts
packages/core/src/controllers/TransactionsController.ts
packages/core/src/index.ts
packages/core/src/utils/FetchUtil.ts
packages/core/src/utils/TypeUtil.ts
packages/scaffold/src/modal/w3m-modal/index.tsx
packages/scaffold/src/partials/w3m-account-activity/index.tsx
packages/scaffold/src/partials/w3m-account-activity/styles.ts
packages/scaffold/src/partials/w3m-account-activity/utils.ts
packages/scaffold/src/partials/w3m-account-wallet-features/index.tsx
packages/ui/src/composites/wui-list-transaction/index.tsx
packages/ui/src/composites/wui-list-transaction/styles.ts
packages/ui/src/composites/wui-list-transaction/utils.ts
packages/ui/src/composites/wui-transaction-visual/index.tsx
packages/ui/src/composites/wui-transaction-visual/styles.ts
packages/ui/src/index.ts
packages/ui/src/utils/TransactionUtil.ts
packages/ui/src/utils/TypesUtil.ts
yarn.lock

Added wallet activity tab
https://github.com/user-attachments/assets/5c816053-7f35-4397-9edb-e67b5bc5dc53
https://github.com/user-attachments/assets/a49fe6e5-60ec-4dda-a520-39137429d5e3
https://linear.app/walletconnect/issue/APKTN-210/view-account-activity

feat: wallet activity

---

.changeset/wet-news-compete.md
packages/ethers/package.json
packages/ethers5/package.json
yarn.lock

Updated ethereum-provider to v2.15.1

chore: updated provider version

---

.changeset/proud-starfishes-care.md
packages/core/src/controllers/EventsController.ts

###
* Use ApiController function to get headers

fix: updated headers function

---

.eslintrc.json
package.json
packages/scaffold/src/modal/w3m-modal/index.tsx
packages/scaffold/src/partials/w3m-all-wallets-list/index.tsx
packages/scaffold/src/partials/w3m-all-wallets-search/index.tsx
packages/scaffold/src/partials/w3m-connecting-mobile/index.tsx
packages/scaffold/src/partials/w3m-connecting-qrcode/index.tsx
packages/scaffold/src/partials/w3m-connecting-web/index.tsx
packages/scaffold/src/partials/w3m-header/index.tsx
packages/scaffold/src/views/w3m-account-view/index.tsx
packages/scaffold/src/views/w3m-all-wallets-view/index.tsx
packages/scaffold/src/views/w3m-connect-view/components/recent-wallet-list.tsx
packages/scaffold/src/views/w3m-connect-view/index.tsx
packages/scaffold/src/views/w3m-connecting-external-view/index.tsx
packages/scaffold/src/views/w3m-connecting-view/index.tsx
packages/scaffold/src/views/w3m-email-verify-device-view/index.tsx
packages/scaffold/src/views/w3m-email-verify-otp-view/index.tsx
packages/scaffold/src/views/w3m-get-wallet-view/index.tsx
packages/scaffold/src/views/w3m-network-switch-view/index.tsx
packages/scaffold/src/views/w3m-networks-view/index.tsx
packages/scaffold/src/views/w3m-update-email-primary-otp-view/index.tsx
packages/scaffold/src/views/w3m-update-email-wallet-view/index.tsx
yarn.lock

chore: added valtio eslint

---

.changeset/chilled-cats-clap.md
packages/siwe/src/index.ts
packages/wallet/src/AppKitAuthWebview.tsx
packages/wallet/src/AppKitFrameConstants.ts
packages/wallet/src/AppKitFrameProvider.ts
packages/wallet/src/AppKitFrameSchema.ts
packages/wallet/src/AppKitFrameTypes.ts

* chore: wait for FRAME_READY event to send messages to frame
* fix: changed import in SIWE package to solve issues with pnpm
Closes https://github.com/reown-com/appkit-react-native/issues/251

chore: added frame_event listener + fix in siwe import

---

.changeset/pretty-news-join.md
packages/wallet/src/AppKitAuthWebview.tsx

* Added timeout before sending messages to frame (email login)

fix: secure frame await

---

.changeset/tender-pumas-reflect.md
packages/siwe/src/index.ts

fix: siwe import

---

.changeset/heavy-hairs-suffer.md
packages/wallet/src/AppKitFrameConstants.ts
packages/wallet/src/AppKitFrameProvider.ts

Changed frame sdk init configuration to make it work with new secure site

fix: changed init config of frame provider

---

.changeset/pretty-taxis-type.md
packages/common/src/contracts/erc20.ts
packages/ethers/src/client.ts
packages/ethers5/src/client.ts
packages/wagmi/src/client.ts

Use token value from prop to get the account balance
Related #255

fix: token balance

---

packages/auth-wagmi/package.json
packages/auth-wagmi/src/index.ts
packages/core/src/controllers/ConnectionController.ts
packages/core/src/controllers/ConnectorController.ts
packages/core/src/utils/StorageUtil.ts
packages/ethers/src/client.ts
packages/ethers5/src/client.ts
packages/scaffold/src/client.ts
packages/scaffold/src/modal/w3m-modal/index.tsx
packages/scaffold/src/views/w3m-connecting-external-view/index.tsx
packages/scaffold/src/views/w3m-connecting-social-view/index.tsx
packages/scaffold/src/views/w3m-connecting-view/index.tsx
packages/wagmi/src/client.ts
packages/wallet/src/AppKitAuthWebview.tsx
packages/wallet/src/AppKitWebview.tsx
yarn.lock

* Interact with secure site only if there's no connection or if the user is connected with email/social
* Small code improvements

refactor: auth connector improvements

---

.changeset/witty-taxis-smell.md
packages/core/src/controllers/ConnectionController.ts
packages/scaffold/src/views/w3m-connecting-external-view/index.tsx
packages/scaffold/src/views/w3m-connecting-social-view/index.tsx

Show wallet view when user logins with an email

fix: show wallet view for email wallets

---

.changeset/mean-elephants-kick.md
apps/native/index.js
apps/native/package.json
package.json
packages/core/src/utils/ApiUtil.ts
packages/scaffold/src/modal/w3m-account-button/index.tsx
packages/ui/src/assets/visual/Profile.tsx
packages/ui/src/components/wui-lean-text/index.web.tsx
packages/ui/src/components/wui-lean-view/index.web.tsx
packages/ui/src/composites/wui-qr-code/index.tsx
yarn.lock

* Small changes to make the sdk work on expo-web (testing)

chore: small changes

---

.changeset/gold-beers-applaud.md
packages/scaffold/src/views/w3m-account-view/index.tsx

Add logic to reload balance every 10secs

fix: refresh balance

---

.changeset/violet-lamps-chew.md
packages/wallet/src/AppKitWebview.tsx

* Changed how social webview renders to solve issues in Android devices

fix: ui changes in social webview to solve android issues

---

packages/core/src/controllers/ConnectionController.ts
packages/core/src/controllers/RouterController.ts
packages/core/src/utils/TypeUtil.ts
packages/scaffold/src/partials/w3m-header/index.tsx
packages/scaffold/src/views/w3m-connect-socials-view/index.tsx
packages/scaffold/src/views/w3m-connect-view/components/social-login-list.tsx
packages/scaffold/src/views/w3m-connecting-farcaster-view/index.tsx
packages/scaffold/src/views/w3m-connecting-social-view/index.tsx
packages/wallet/src/AppKitWebview.tsx

* Added `SOCIAL_LOGIN_CANCELED` & `SOCIAL_LOGIN_REQUEST_USER_DATA` events
* Setting selected provider in `ConnectionController` instead of sending as a route param
https://linear.app/reown/issue/APKTN-353/add-new-social-event-names-in-react-native

chore: send new social events

---

packages/scaffold/src/partials/w3m-header/index.tsx
packages/scaffold/src/views/w3m-connecting-farcaster-view/index.tsx

* Added temporary workaround to reload auth site if farcaster flow is closed

fix: farcaster login refresh

---

.github/workflows/changesets.yml
.github/workflows/e2e.yml
.github/workflows/pull-request.yml
.github/workflows/verify.yml

Add e2e action to pull requests and release

chore: added e2e in pull request action

---

apps/native/App.tsx
packages/core/src/utils/ConstantsUtil.ts
packages/core/src/utils/TypeUtil.ts

Disable farcaster login until issue on iOS is solved

chore: disabled farcaster login

---

.changeset/weak-poems-play.md
packages/ethers/package.json
packages/ethers5/package.json
yarn.lock

Updated ethereum-provider to 2.17.3 in ethers packages

chore: updated ethereum provider version

---

.github/workflows/changesets.yml
package.json

* Disabled custom github release creation as changesets doesn't work well if tag creation is disabled
related: https://github.com/changesets/action/issues/141

chore: create github releases using changesets

---

.changeset/proud-badgers-provide.md
packages/wagmi/src/client.ts

* Fixed initial "connecting" loader when there was no previous connection
* Fixed loader issue when switching between EOA and Smart Account

fix: wagmi loaders

---

.changeset/purple-berries-marry.md
packages/core/src/controllers/ConnectorController.ts
packages/core/src/controllers/RouterController.ts

Changed the way arrays are updated in Valtio's state to maintain immutability principles
#313

fix: improved state array updates in connection and router controllers

---

.changeset/witty-melons-brush.md
packages/core/src/controllers/BlockchainApiController.ts
packages/core/src/utils/ApiUtil.ts

* Send expo info in userAgent
* Send origin in blockchain endpoints

chore: changes in useragent

---

packages/scaffold/src/partials/w3m-account-activity/index.tsx
packages/scaffold/src/partials/w3m-account-activity/styles.ts

fix: showing loader and placeholder correctly on activity tab

fix: loader issue activity tab

---

package.json
yarn.lock

Added yarn resolutions to solve dependabot alerts

chore: added resolutions to solve dependabot alerts

---

.changeset/shaggy-moose-tan.md
packages/scaffold/src/partials/w3m-all-wallets-list/index.tsx
packages/scaffold/src/views/w3m-connect-view/components/all-wallet-list.tsx

Fix issue caused when rendering installed wallets along the rest of the wallet list

fix: deduplicate wallets in all-wallets view

---

packages/appkit/src/AppKit.ts
packages/appkit/src/modal/w3m-account-button/index.tsx
packages/appkit/src/modal/w3m-button/index.tsx
packages/appkit/src/modal/w3m-network-button/index.tsx
packages/appkit/src/partials/w3m-account-activity/index.tsx
packages/appkit/src/partials/w3m-account-tokens/index.tsx
packages/appkit/src/partials/w3m-selector-modal/index.tsx
packages/appkit/src/utils/NetworkUtil.ts
packages/appkit/src/views/w3m-account-default-view/index.tsx
packages/appkit/src/views/w3m-account-view/index.tsx
packages/appkit/src/views/w3m-network-switch-view/index.tsx
packages/appkit/src/views/w3m-networks-view/index.tsx
packages/appkit/src/views/w3m-onramp-checkout-view/index.tsx
packages/appkit/src/views/w3m-onramp-view/index.tsx
packages/appkit/src/views/w3m-swap-view/components/select-token-view/index.tsx
packages/appkit/src/views/w3m-unsupported-chain-view/index.tsx
packages/appkit/src/views/w3m-wallet-compatible-networks-view/index.tsx
packages/appkit/src/views/w3m-wallet-receive-view/index.tsx
packages/appkit/src/views/w3m-wallet-send-preview-view/components/preview-send-details.tsx
packages/appkit/src/views/w3m-wallet-send-select-token-view/index.tsx
packages/core/src/controllers/ConnectionsController.ts
packages/core/src/controllers/ModalController.ts
packages/core/src/controllers/OptionsController.ts
packages/core/src/utils/AssetUtil.ts
packages/ui/src/composites/wui-network-image/index.tsx

* Improved default network logic
* Show default network in network button and allow user to change the default network before connecting
- **Removed `defaultNetwork` Property**: The `defaultNetwork` property has been removed from `AppKit`, and its functionality has been replaced with `OptionsController.state.defaultNetwork`. This simplifies the configuration and ensures consistent handling of default networks across the application. [[1]](diffhunk://#diff-3682d6df4945029dc63dcd74cbe7c82918ca879287935c7919862f24f0633559L74) [[2]](diffhunk://#diff-3682d6df4945029dc63dcd74cbe7c82918ca879287935c7919862f24f0633559L100-L102) [[3]](diffhunk://#diff-3682d6df4945029dc63dcd74cbe7c82918ca879287935c7919862f24f0633559L573-R595)
- **Enhanced Default Chain ID Logic**: The `getDefaultChainId` method in …

fix: default network + network button

---

.changeset/spicy-friends-play.md
packages/ethers/package.json
packages/ethers5/package.json
yarn.lock

Update `@walletconnect/ethereum-provider` to `2.21.5`

chore: bump ethereum-provider version

---

.changeset/clever-towns-search.md
packages/core/src/utils/TypeUtil.ts
packages/scaffold/src/views/w3m-account-default-view/index.tsx
packages/wallet/src/AppKitFrameSchema.ts

Fix account type switching from account view

fix: switching account type in universal wallets

---

packages/appkit/src/AppKit.ts
packages/appkit/src/partials/w3m-account-wallet-features/index.tsx
packages/appkit/src/views/w3m-account-view/index.tsx
packages/bitcoin/src/adapter.ts
packages/ethers/src/adapter.ts
packages/solana/src/adapter.ts
packages/wagmi/src/connectors/UniversalConnector.ts

* Fixed an issue that blocked network switching
* Watch account balance on Account views
https://linear.app/reown/issue/APKTN-588/after-switching-network-activity-page-is-empty
https://linear.app/reown/issue/APKTN-587/balance-is-never-updated
https://linear.app/reown/issue/APKTN-586/cannot-switch-network

fix: small fixes

---

apps/native/App.tsx
packages/appkit/src/hooks/useRouteTransition.ts
packages/appkit/src/partials/w3m-connecting-qrcode/components/ReownButton.tsx
packages/appkit/src/partials/w3m-connecting-qrcode/index.tsx
packages/appkit/src/partials/w3m-connecting-qrcode/styles.ts
packages/appkit/src/utils/HelpersUtil.ts
packages/appkit/src/utils/UiUtil.ts
packages/appkit/src/views/w3m-all-wallets-view/index.tsx
packages/appkit/src/views/w3m-connect-view/components/custom-wallet-list.tsx
packages/appkit/src/views/w3m-connect-view/index.tsx
packages/appkit/src/views/w3m-connecting-external-view/index.tsx
packages/common/src/types/api/wallet-api.ts
packages/common/src/utils/ConstantsUtil.ts
packages/core/src/controllers/ApiController.ts
packages/ui/src/components/wui-shimmer/index.tsx

**Wallet Management Improvements**
* Custom wallets are now checked for installation status and merged into the installed wallets list, allowing for more accurate filtering and display across the app. (`ApiController.ts` and related logic) [[1]](diffhunk://#diff-a6365f27a59e9d02aa3c3ffbd89e0d0f9c5bfe679873f5002efdd527500c2563L111-R110) [[2]](diffhunk://#diff-a6365f27a59e9d02aa3c3ffbd89e0d0f9c5bfe679873f5002efdd527500c2563R132-R138) [[3]](diffhunk://#diff-a6365f27a59e9d02aa3c3ffbd89e0d0f9c5bfe679873f5002efdd527500c2563R165-R175) [[4]](diffhunk://#diff-e36a0463f442f4aa01980558a4a9f3a754eea94eedb5c5fd074f96b78d441c96L33-R39)
* The `CustomWallet` type and wallet constants have been extended to include `android_app_id` and `ios_schema`, supporting more reliable app detection and deep linking. …

fix: added check installed for custom wallets + animation issues on android

---

.github/workflows/cta.yml

Added CLA bot for external contributors

chore: added cla bot for external contributors

---

apps/native/package.json
package.json
packages/appkit/package.json
packages/appkit/src/AppKit.ts
packages/appkit/src/connectors/WalletConnectConnector.ts
packages/appkit/src/modal/w3m-router/index.tsx
packages/appkit/src/views/w3m-network-switch-view/index.tsx
packages/appkit/src/views/w3m-network-switch-view/styles.ts
packages/appkit/src/views/w3m-networks-view/index.tsx
packages/appkit/src/views/w3m-unsupported-chain-view/index.tsx
packages/common/src/types/wallet/connection.ts
packages/core/src/controllers/ConnectionsController.ts
packages/core/src/controllers/RouterController.ts
packages/core/src/utils/ConstantsUtil.ts
packages/ethers/package.json
packages/ui/src/composites/wui-card-select/index.tsx
packages/wagmi/src/connectors/UniversalConnector.ts
yarn.lock

**Network Switching and Views:**
* Added a new `NetworkSwitchView` component and route, providing a dedicated UI for handling network switch requests and errors, including retry logic. This is useful for wallets like metamask that allow to add chains after the connection (`packages/appkit/src/views/w3m-network-switch-view/index.tsx`, `packages/appkit/src/views/w3m-network-switch-view/styles.ts`, `packages/appkit/src/modal/w3m-router/index.tsx`) [[1]](diffhunk://#diff-b0b7d62a13f28383807c7b80f80117d4e4c2adcd6060a08abc467473b1c3efa0R1-R104) [[2]](diffhunk://#diff-5b3b0cf08db49dc256fd936d4fb490e64852ea48b0fd4c2f8127ea22a675caf7R1-R23) [[3]](diffhunk://#diff-2c7168f7d244d110f083d841243d20be5d4d22ccb3f23b0df06befb8483906e7R16) [[4]](diffhunk://#diff-2c7168f7d244d110f083d841243d20be5d4d22ccb3f23 …

fix: added option to add chains in metamask connections + improvements
