reown-com/appkit-react-native

.github/docs/development.md
README.md

Added docs based on web3modal web documentation

feat: added docs

---

src/hooks/useWeb3Modal.ts

* Added `address` prop in `useWeb3Modal` hook to show the connected address when connected
Updated docs:
https://github.com/WalletConnect/web3modal-react-native/issues/33
https://github.com/orgs/WalletConnect/discussions/2442

feat: added connected address to web3modal hook

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml

* Added a new issue template similar to [this template](https://github.com/facebook/react-native/issues/new?assignees=&labels=Needs%3A+Triage+%3Amag%3A&projects=&template=bug_report.yml)
* Added contact links similar to the bottom links of [this](https://github.com/facebook/react-native/issues/new/choose)
This same template will be added to [react-native-examples](https://github.com/WalletConnect/react-native-examples)

chore: added issue template and contact links

---

src/assets/Checkmark.tsx
src/assets/Warning.tsx
src/components/ModalToast.tsx
src/components/NavHeader.tsx
src/components/QRCode.tsx
src/components/Touchable.tsx
src/components/ViewAllBox.tsx
src/components/WalletItem.tsx
src/components/Web3Button.tsx
src/components/Web3ModalHeader.tsx
src/config/animations.ts
src/constants/Colors.ts
src/controllers/RouterCtrl.ts
src/hooks/useConfigure.ts
src/index.tsx
src/utils/ExplorerUtil.ts
src/utils/UiUtil.ts
src/views/Account.tsx
src/views/InitialExplorer.tsx
src/views/QRCodeView.tsx
src/views/ViewAllExplorer.tsx

* Improved toast UI
* Added animation to view transitions
* Added scale effect to buttons
* Solved QR View flickering issue
https://github.com/WalletConnect/web3modal-react-native/assets/25931366/c69411e9-a9b2-4ed7-9e9d-37a1f29d928d
https://github.com/WalletConnect/web3modal-react-native/assets/25931366/e03d9ce7-3988-49d7-af77-2a37558c0721
https://github.com/WalletConnect/web3modal-react-native/assets/25931366/8f9ea97c-c904-4e5d-b776-c3b5afd76863
https://github.com/WalletConnect/web3modal-react-native/assets/25931366/0b8d34db-5c6b-42ab-ab55-ef28eb06a4d4

feat: UI updates

---

packages/core/src/controllers/ConnectionController.ts
packages/scaffold/src/views/w3m-all-wallets-view/index.tsx

* Clean `pressedWallet` if the user presses QR button in all wallets list

fix: clean pressed wallet if user press qr button

---

packages/core/src/controllers/ApiController.ts
packages/core/src/utils/TypeUtils.ts
packages/scaffold/src/partials/w3m-all-wallets-list/index.tsx
packages/scaffold/src/partials/w3m-all-wallets-search/index.tsx
packages/ui/src/composites/wui-card-select/index.tsx

* Adding loading items dynamically to wallet list
The page loader needs to be dynamic to cover this cases:
The length of the wallet list is dynamic because: 
* Items per row is dynamic based on screen width
* Preloaded wallets before opening "All wallets" view is also dynamic based on recommended, featured and installed wallets
So if i want to show a page loader at bottom, i need to fill the empty spaces in the row
Calculate how many wallets i need to fill the gap, and add those items at the bottom of the list
https://github.com/WalletConnect/web3modal-react-native/assets/25931366/a68cbd2c-85b0-4e62-9f76-58e90207410a
https://github.com/WalletConnect/web3modal-react-native/assets/25931366/8098c05b-32d0-417d-824c-f0898ffa7cad

fix: improved page loading shimmer items

---

packages/core/src/controllers/ConnectionController.ts
packages/scaffold/src/views/w3m-all-wallets-view/index.tsx

* Fixed an issue when the user selects a wallet but then decides to connect using a QR code. Now the linking is cleared so the provider doesn't redirect to the wrong app

fix: clear linking if qr is pressed

---

packages/wagmi/src/connectors/WalletConnectConnector.ts
packages/wagmi/src/utils/defaultWagmiConfig.ts
packages/wagmi/src/utils/storageUtils.ts

* Using asyncstorage in custom wagmi connector instead of `this.storage`
Note: Wagmi allows to setup a custom storage but apparently it doesn't support async functions.
https://github.com/WalletConnect/web3modal-react-native/issues/78

fix: using asyncstorage in connector

---

packages/ui/src/composites/wui-account-button/styles.ts

Account View with no Balance Shown had some UI discrepancies
- Change the margin / padding
- Not sure if you want to keep it as passing(3xs) or normal xs

Change account UI margin left

---

packages/scaffold/src/partials/w3m-all-wallets-list/index.tsx
packages/scaffold/src/partials/w3m-all-wallets-search/index.tsx
packages/scaffold/src/views/w3m-connect-view/index.tsx
packages/ui/src/composites/wui-card-select/index.tsx
packages/ui/src/composites/wui-card-select/styles.ts
packages/ui/src/composites/wui-icon-box/index.tsx
packages/ui/src/composites/wui-list-wallet/index.tsx
packages/ui/src/composites/wui-list-wallet/styles.ts

* Added installed icon below installed wallets
https://github.com/WalletConnect/web3modal/issues/1523

feat: added installed icon

---

packages/core/src/controllers/ApiController.ts
packages/scaffold/src/views/w3m-connect-view/index.tsx

Added installed wallets in "All wallets" button count. Fixes edge case where includedWalletIds < 10 and those wallets are installed. Before the count was showing "0" despite there were wallets in the list
testing with
```
includeWalletIds: [
'1ae92b26df02f0abca6304df07debccd18262fdf5fe82daa81593582dac9a369',
'4622a2b2d6af1c9844944291e5e7351a6aa24cd7b23099efac1b2fd875da31a0',
],
```

fix: added installed wallets in total count

---

packages/wagmi/src/client.ts

* Compare connector types instead of the id. This issue was causing not to go back automatically to the profile view after switching the network with some wallets

fix: compare connector type instead of id

---

packages/ethers5/package.json
yarn.lock

* `@walletconnect/ethereum-provider` is now a package dependency (instead of a peerDep)

fix: added ethereum provider as a dependency

---

.changeset/curvy-toys-press.md
.changeset/pre.json
packages/ethers5/CHANGELOG.md
packages/ethers5/package.json

* fix: added ethereum provider as a dependency by @ignaciosantise in https://github.com/WalletConnect/web3modal-react-native/pull/131

chore: bump ethers5 to v1.2.0-alpha.1

---

.changeset/purple-humans-wink.md
packages/core/src/controllers/ApiController.ts
packages/core/src/utils/CoreHelperUtil.ts

Apparently there's an issue with Sentry in newer versions of React Native that cause `Promise.allSettled` to fail. Adding a workaround until it's solved

fix: Promise.allSettled is undefined

---

.changeset/modern-ghosts-sing.md
packages/core/package.json
packages/siwe/package.json
yarn.lock

Bump `valtio` version to 1.11.2 to match appkit web sdk

chore: bump valtio to v1.11.2

---

.changeset/good-cats-double.md
packages/coinbase-wagmi/src/index.ts
packages/email-wagmi/src/index.ts
packages/wagmi/src/connectors/WalletConnectConnector.ts

The new version of Wagmi removed the type `Evaluate` from it's core causing a TS error.
According to their docs, there's no need to use it:
https://wagmi.sh/dev/creating-connectors#_3-create-the-connector-object

fix: removed wagmi Evaluate type from connectors

---

.github/actions/setup/action.yml

use `actions/setup-node@v4` cache instead of manual cache

chore: cache action

---

.changeset/forty-phones-begin.md
packages/core/src/controllers/ApiController.ts
packages/core/src/utils/StorageUtil.ts
packages/scaffold/src/utils/UiUtil.ts
packages/scaffold/src/views/w3m-connect-view/components/all-wallet-list.tsx
packages/scaffold/src/views/w3m-connecting-external-view/index.tsx

* Update recent wallet info saved in local storage when fetching new data from API
This will help keeping the local storage data up to date with the wallets cloud settings
The dapp has old data saved in recent wallets. But it's updated after the sdk fetches new data from API
https://github.com/user-attachments/assets/8a16dedf-ad57-4f47-8620-be211f92a7e2

fix: update recent wallets info after fetching

---

.changeset/famous-impalas-learn.md
packages/scaffold/src/client.ts

Remove coinbase wallet from list if the connector is not set, so it doesn't fail if the user selects it
https://github.com/user-attachments/assets/3856869e-f3fd-4bc2-8835-5d00ddc69c4d
https://github.com/user-attachments/assets/4cabc562-ff3b-4c9f-93a5-1b69810117b9
https://github.com/user-attachments/assets/d6a5b1d1-17bd-4d68-bc8a-a955abf5d773
https://github.com/user-attachments/assets/a8184a31-67a2-4309-a9fb-94883bad8e4c
https://linear.app/walletconnect/issue/APKTN-247

fix: check coinbase connector

---

.changeset/twenty-boxes-grab.md
packages/ethers/src/client.ts
packages/ethers5/src/client.ts

Removed workaround for MM that called `wallet_addEthereumChain` if the session didn't contain the requested chain

fix: removed addChain call in switch chain method

---

.changeset/wild-masks-pay.md
packages/core/src/controllers/ConnectionController.ts
packages/scaffold/src/views/w3m-connecting-view/index.tsx

* If the user declines the connection request, clear the uri + pairing expiration so it generates a new one
* subscribe to expiry check only if the user is in QR view
https://github.com/user-attachments/assets/b71f4216-434a-49bc-9088-ec03fa9e9a42
https://linear.app/walletconnect/issue/WK-328/rn-dapp-swift-wallet-after-declining-once-from-the-wallet-approval-is

fix: reset pairing if it fails

---

.changeset/red-ladybugs-matter.md
package.json
packages/ethers/package.json
packages/ethers5/package.json
yarn.lock

Updated `@walletconnect/ethereum-provider` to `2.17.2` in Ethers and Ethers5 packages

chore: bump walletconnect deps to 2.17.2 in ethers packages

---

.changeset/late-cycles-lick.md
apps/native/App.tsx
packages/common/src/utils/TypeUtil.ts
packages/core/src/__tests__/controllers/ThemeController.test.ts
packages/core/src/controllers/ThemeController.ts
packages/core/src/utils/TypeUtil.ts
packages/scaffold/src/client.ts
packages/scaffold/src/modal/w3m-account-button/index.tsx
packages/scaffold/src/modal/w3m-connect-button/index.tsx
packages/scaffold/src/modal/w3m-modal/index.tsx
packages/scaffold/src/modal/w3m-network-button/index.tsx
packages/scaffold/src/views/w3m-account-default-view/components/auth-buttons.tsx
packages/scaffold/src/views/w3m-account-default-view/index.tsx
packages/ui/package.json
packages/ui/src/context/ThemeContext.tsx
packages/ui/src/hooks/useTheme.ts
packages/ui/src/index.ts
packages/ui/src/utils/ThemeUtil.ts
yarn.lock

* Added `themeMode` prop to override default theme of the modal
* Added `themeVariables` prop to override accent color
https://linear.app/reown/issue/APKTN-367

feat: added ability to change themeMode and override accent color

---

.changeset/empty-mangos-push.md
.maestro/w3m-connect-flow.yaml
apps/native/tests/shared/constants/index.ts
apps/native/tests/shared/constants/timeouts.ts
apps/native/tests/shared/pages/ModalPage.ts
apps/native/tests/shared/pages/WalletPage.ts
apps/native/tests/shared/types/index.ts
apps/native/tests/shared/utils/timeouts.ts
apps/native/tests/shared/validators/ModalValidator.ts
apps/native/tests/wallet.spec.ts
packages/scaffold/src/modal/w3m-modal/index.tsx
packages/scaffold/src/partials/w3m-account-activity/index.tsx
packages/scaffold/src/views/w3m-account-default-view/index.tsx
packages/ui/src/components/wui-loading-spinner/index.tsx

Load transactions only when the user enters activity tab/screen

fix: load transactions only when needed

---

.changeset/few-cherries-leave.md
packages/ethers/src/client.ts
packages/ethers5/src/client.ts
packages/wagmi/src/client.ts

* Added logic to cover failures when trying to get account's balance.
https://github.com/reown-com/appkit-react-native/issues/319

fix: clear balance if the sdk fails to get it

---

.changeset/two-bikes-wave.md
packages/scaffold/src/partials/w3m-all-wallets-list/index.tsx

* Check for loaders before loading a new page in all wallet lists. This was causing an issue of multiple pages being loaded at the same time

fix: check loaders before loading new page of wallets

---

.changeset/thin-files-play.md
packages/scaffold/src/modal/w3m-modal/index.tsx

Disabled `coverScreen` prop to solve issues with expo-router on Android

fix: disable cover screen in modal

---

.changeset/soft-waves-heal.md
packages/scaffold/src/views/w3m-connecting-social-view/index.tsx

Fixed issue with Apple Login that hanged the view

fix: hanged Apple Login view

---

.changeset/rotten-pianos-argue.md
.eslintrc.json
packages/core/src/__tests__/utils/FetchUtil.test.ts
packages/core/src/utils/FetchUtil.ts

This pull request introduces several updates, including enhancements to URL generation logic, additional test coverage for the `FetchUtil` utility, and minor configuration changes. The most significant changes focus on improving the handling of URL construction and query parameters in the `FetchUtil` class.
* Refactored the `createUrl` method in `FetchUtil` to replace the use of the `URL` class with custom logic for constructing URLs. This change ensures compatibility with environments that lack `URL` support. The new implementation handles absolute and relative paths, trailing slashes, and query parameter encoding more robustly. (`packages/core/src/utils/FetchUtil.ts`)
* Added comprehensive unit tests for the `FetchUtil` utility, specifically for the `createUrl` method. These tests cover …

chore: replace internal URL usage

---

.changeset/six-dots-punch.md
packages/core/src/utils/AssetUtil.ts
packages/scaffold/src/modal/w3m-account-button/index.tsx
packages/scaffold/src/modal/w3m-network-button/index.tsx
packages/scaffold/src/partials/w3m-account-activity/index.tsx
packages/scaffold/src/partials/w3m-account-tokens/index.tsx
packages/scaffold/src/partials/w3m-selector-modal/index.tsx
packages/scaffold/src/views/w3m-account-default-view/index.tsx
packages/scaffold/src/views/w3m-account-view/index.tsx
packages/scaffold/src/views/w3m-network-switch-view/index.tsx
packages/scaffold/src/views/w3m-networks-view/index.tsx
packages/scaffold/src/views/w3m-onramp-view/index.tsx
packages/scaffold/src/views/w3m-swap-select-token-view/index.tsx
packages/scaffold/src/views/w3m-unsupported-chain-view/index.tsx
packages/scaffold/src/views/w3m-wallet-compatible-networks-view/index.tsx
packages/scaffold/src/views/w3m-wallet-receive-view/index.tsx
packages/scaffold/src/views/w3m-wallet-send-preview-view/components/preview-send-details.tsx
packages/scaffold/src/views/w3m-wallet-send-select-token-view/index.tsx
packages/ui/src/composites/wui-card-select/index.tsx
packages/ui/src/composites/wui-network-image/index.tsx

This pull request addresses a bug with displaying network images in the React Native appkit packages. The main change is to ensure network images are shown correctly across the app by updating how network image data is accessed and passed through various components. The fix involves modifying the `AssetUtil.getNetworkImage` utility to accept a `networkImages` mapping and updating all usages to provide this data from `AssetController.state`.
**Bug fix: Network images display**
* Updated `AssetUtil.getNetworkImage` to accept a second parameter, `networkImages`, allowing it to reliably fetch network images using either the network's `imageUrl` or its `imageId` from the provided mapping.
* Refactored all components and views that display network images (e.g., `AccountButton`, `NetworkButton`, …

fix: network images loading

---

apps/native/src/components/DisconnectButton.tsx
apps/native/src/components/OpenButton.tsx
apps/native/src/views/WagmiActionsView.tsx
packages/appkit/src/AppKit.ts
packages/common/src/types/api/wallet-api.ts
packages/core/src/controllers/ConnectionsController.ts

**Connection state management refactor:**
* Refactored connection updates in `ConnectionsController.ts` to use a new `updateConnection` helper, centralizing logic for updating connections and returning the updated object. This improves code maintainability and reduces duplication. [[1]](diffhunk://#diff-68c9947de03833ee5f6205e289907e422a90b7028de3f64f125e9165882f7079L83-R89) [[2]](diffhunk://#diff-68c9947de03833ee5f6205e289907e422a90b7028de3f64f125e9165882f7079L260-R266) [[3]](diffhunk://#diff-68c9947de03833ee5f6205e289907e422a90b7028de3f64f125e9165882f7079L336-R339) [[4]](diffhunk://#diff-68c9947de03833ee5f6205e289907e422a90b7028de3f64f125e9165882f7079L384-R384)
* Added a guard in `setActiveNamespace` to avoid unnecessary state updates if the namespace hasn't changed.
**Type and API …

Fix: update state correctly after switching chain + small changes

---

packages/appkit/src/AppKit.ts
packages/appkit/src/modal/w3m-modal/index.tsx
packages/core/src/controllers/ThemeController.ts

Theme management improvements:
* Added a `defaultThemeMode` property to the `ThemeController` state and implemented a new `setDefaultThemeMode` method that sets both the default and active theme mode. (`packages/core/src/controllers/ThemeController.ts`) [[1]](diffhunk://#diff-33cbf4f96e58e19ce2eb03efc85d1f8a1441bbfcf8d4ee5b389aba008b4fe643R8-R15) [[2]](diffhunk://#diff-33cbf4f96e58e19ce2eb03efc85d1f8a1441bbfcf8d4ee5b389aba008b4fe643R35-R39)
* Updated `AppKit` initialization to use `ThemeController.setDefaultThemeMode` instead of directly setting the theme mode, ensuring the default is tracked and applied consistently. (`packages/appkit/src/AppKit.ts`)
System color scheme support:
* In the modal component, added support for detecting the system color scheme using `useColorScheme` and, if …

feat: change appkit theme mode automatically if no default value is set
